### ISSUE TITLE
Game not lauching after changing Overlay settings.

### ISSUE THREAD

**Issue by UrsoManso** [TekkenOverlay/TekkenOverlay#107]
Just downloaded the newest version of Tekken Overlay but for some reason after making my usual changes the games crashes everytime I try to launch the game again.

Here's the log. https://pastebin.com/dPsysWAD

**Comment by faileon** [comment]
Mine is also crashing - I created bat file to start both game and tekken overlay at the same time, but starting it this way the game wont start after I edited settings. If I however start the game first via steam and then the overlay, it works. Are you experiencing the same?

**Comment by ParkourGrip** [comment]
Unfortunately, the error handling in Tekken Overlay is not as good as it should be.
Its hard to figure out anything usefull from the logs.
However, I did notice that the new version of TO is not as stable as before by trying it out for 10 minutes.
These days it has been mostly only Kula maintaining the project and making updates.
IRL work is taking priority for me and I have barely any time to play games yet alone ensure that Kulas updates are stable.
The main issues that happens when Kula works alone is that both his Tekken and Windows is heavenly modified and that is not a good representation of the average Tekken Overlay user's system.
I guess I'll have to do some testing and debugging this weekend to figure out what is going on.

**Comment by KulaGGin** [comment]
Try [the new 5.10.1 release](https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.10.1) and see if it works.

**Comment by UrsoManso** [comment]
I got a warning the first time I launched Tekken with overlay but no crashes afterwards, everything seems to be working as usual.

**Comment by UrsoManso** [comment]
> If I however start the game first via steam and then the overlay, it works. Are you experiencing the same?

I haven't tried that way, I assumed Overlay had to be running prior to the game.

**Comment by KulaGGin** [comment]
> I assumed Overlay had to be running prior to the game.

It's supposed to work in either case.

**Comment by Hyundai0** [comment]
> > I assumed Overlay had to be running prior to the game.
> 
> It's supposed to work in either case.
 not working in my case

**Comment by KulaGGin** [comment]
> not working in my case

What version of the overlay are you running?

**Comment by ParkourGrip** [comment]
Played a few hours with the new version today. No crashes.

**Comment by Hyundai0** [comment]
> > not working in my case
> 
> What version of the overlay are you running?

5.10.1

**Comment by faileon** [comment]
Latest version is working well so far, thanks Kula

**Comment by SOYMILK90** [comment]
![image](https://user-images.githubusercontent.com/120939427/208300878-e020e72d-7c52-41e7-8fe7-b08810fc146a.png)
If I run 5.10.1 ver overlat and play game, game crash and not run
