### ISSUE TITLE
With overlay on, there is added delay to reading inputs after quick restart.

### ISSUE THREAD

**Issue by BenHR555** [TekkenOverlay/TekkenOverlay#110]
This doesn't affect most use cases of training mode so I get that this isn't a high priority. However, when doing backdash practice/testing setups like [this](https://www.reddit.com/r/Tekken/comments/dbdow9/teal_rank_backdash_challenge/), with the overlay on, there is a slight but noticeable added delay to when the game will read inputs after every quick restart. It becomes noticeable when doing quick restart-based setups in training mode that require really fast inputs. If this could be fixed at some point that would be great, although I'm not holding my breath.

Edit: Tested with all combinations of "restart manager" settings, still present. Turned off all settings possible in the overlay just in case, still present. The only way to get the delay to go away is to close the overlay and completely restart Tekken.

**Comment by KulaGGin** [comment]
I can't reproduce. After I press Select+3 and immediately hold B input, my character starts moving on the 18th game frame in both cases.
Can you record a video without the overlay, then with overlay after, and post it?

**Comment by KulaGGin** [comment]
> the clip:
> https://user-images.githubusercontent.com/73731284/209257988-e80d2dd1-a687-46f8-ae7c-a6aca4dd542b.mp4

> A few frames after loading the quick restart I input b.

In this video with the overlay you pressed first b input on the 14th frame after the restart. The game shouldn't and doesn't register inputs until 18th frame after the restart. That's the behavior with or without the overlay.

> Compare it to what happens without the overlay on.
> You also have to go frame-by-frame to see with this one.
> https://user-images.githubusercontent.com/73731284/209258277-f2f5cf87-dd21-4ea9-ac94-b3723390bdd0.mp4

This video starts in the middle of the restart, so it's impossible to tell on which frame after the restart you pressed the button. Record it, so we can see at least a few frames before the screen goes black.

**Comment by KulaGGin** [comment]
Well, yes, you see, you held back input up until 17th frame(including), and it was processed and showed up on the 18th frame by the game. But with the overlay you held back only up until 14th frame, and the game didn't process it, because it only starts doing it on the 18th frame.

So there is no additional delay with the overlay
![](https://cdn.discordapp.com/emojis/581918526135074818.webp?size=48&quality=lossless)

**Comment by ParkourGrip** [comment]
@BenHR555 It's possible that because you unlocked the frame-rate, your UI animations got faster. That made the fade in animation faster. That fooled you into thinking that it takes longer for your inputs to start getting processed. When in reality the fade in animation just got faster leaving you longer fully faded in without processed inputs.
