### ISSUE TITLE
Repeat action manager

### ISSUE THREAD

**Issue by ZataraTMM** [TekkenOverlay/TekkenOverlay#112]
How does this feature work?

**Comment by KulaGGin** [comment]
In the game in practice mode choose menu CPU Action 1 and then Repeat Action. Then in the Repeat Action 1 menu select MoveList and scroll moves from the movelist. In the Repeat Action Manager in the overlay you'll see how selected move ID changes when you scroll the move list. Press Add button to add the move to the list of moves to repeat. Add as many as you want. After that choose any move from the move list in the game with the **A** button so that Repeat Action 1 is active in the game. Then just press **Select+B** to start playing the moves just as you do normally. The moves that are in the Repeat Action Manager will be played instead of the move that you chose in the game.
