### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml found in download.

### ISSUE THREAD

**Issue by compsyguy** [TekkenOverlay/TekkenOverlay#42]
I tried to get the new version from here:
https://github.com/TekkenOverlay/TekkenOverlay
and my virus scan said it found the Wacatac trojan.

**Comment by TueurDeBrioche** [comment]
same  ?  is it safe to use this tekken overlay ? 

> I tried to get the new version from here:
> https://github.com/TekkenOverlay/TekkenOverlay
> and my virus scan said it found the Wacatac trojan.

**Comment by KulaGGin** [comment]
Just a false positive, don't trust your one antivirus.
Here's a scan on virustotal of the last version by many vendors of the tekken-overlay-run.exe file:
https://www.virustotal.com/gui/file/46f258fcb15a5a3825bfd919901e73800395ab37d44c8577d23ce8829015954c/detection

Here's the scan of the first released version(the 3.33 one) of the tekken-overlay-run.exe:
https://www.virustotal.com/gui/file/6250473210b47f87a25afac8d6dc9bb5a4a55c30469f73a5600684a40d5f4d0a/detection

Just a few false positive results.

Also, the tekken-overlay-run.exe file is just an injector, it loads the tekken-overlay.dll into Tekken's process and starts to run it. The tekken-overlay.dll file is clean for all vendors on virustotal:
https://www.virustotal.com/gui/file/f676e72af77fde6d16602879bc61aee9480d697fcc731ad92998e001a5495d75/detection

You can use any injector to inject the dll into Tekken's process and not use the tekken-overlay-run.exe file at all.

**Comment by ParkourGrip** [comment]
Its funny that this version of the exe is marked differently since the source code of the exe part did not change from the last version at all.

You can use the `tekken-overlay-run.exe` from any version of tekken overlay. All the updates are in the `tekken-overlay.dll`.

Whether or not this software is safe to use... 
I can tell you that it is but there is no way for me to proof to you that it really is.
It's up to you to decide whether you trust us or not.

**Comment by thoraero** [comment]
Thanks for the update sir. 
I had the same issue. Thanks for your explanation. It's working fine here. I assure you compsyguy, nothing amusing happened so far. 
But I have one tiny question to ask - why am I seeing [overlay] in front of my name? Can I no longer be a secret cheater who just want to play casually without remembering thousands of frame data info?

**Comment by ParkourGrip** [comment]
I guess the issue is solved.

**Comment by ParkourGrip** [comment]
I'm going to write the summary of this issue here.

Whenever we release compile a new version of the overlay the antivirus software seems to mark the `tekken-overlay-run.exe` as a virus.

This is probably because this executable file injects `tekken-overlay.dll` into the `TekkenGame-Win64-Shipping.exe` process and DLL injection is considered to be a shady operation when it comes to antivirus software.

For unknown reasons `tekken-overlay-run.exe` that is shipped with older versions of the overlay stop being marked as viruses when a some amount of time passes.

The source code of `tekken-overlay-run.exe` has not changed for more then a year but our build script compiles a new instance of it every time we release a new version of the overlay.

1) So one way to stop the antivirus software complaining about it is to add a exception for the `tekken-overlay-run.exe` file.

2) Another way is to download a older version of the overlay and replace the `tekken-overlay-run.exe` file from the new version with one from the old version. This file dose the same thing on every version of the overlay and is interchangeable. 
All the overlay updates are inside the `tekken-overlay.dll`.

3) Third option is not to use the `tekken-overlay-run.exe` injector that comes with the overlay but to use a third party injector.
Make sure you trust whoever makes the third party injector. 
We made our own injector because we did not trust any that we found online. 

Keep in mind that that using any of these methods dose not prove that Tekken Overlay dose not contain any malicious code.
At the end of the day you have to trust our team that we will not put anything malicious inside the `tekken-overlay.dll`.
Using any of the methods above you are equally susceptible to anything that we could possibly put inside the `tekken-overlay.dll`.

Ultimately the thing that would prove that there is no malicious code inside is making the source code available to the public.
However, if we were to do that the script kiddies would instantly start using this project as the base code to make cheats.
You would get a forked version of the overlay with the "[overlay]" name-tag disabled.
They are already doing similar things with the Tekken Bot Prime project currently.
