### ISSUE TITLE
The tag [overlay] feature needs to be reworked

### ISSUE THREAD

**Issue by vissegard** [TekkenOverlay/TekkenOverlay#44]
I am 100% behind the idea of informing people that you use overlay to your advantage against players online. But right now, this feature is harmful to: a) for people that want to take an advantage out of it (good)
b) people that just want to use it for practice mode purposes
c) people that were using it to actually measure lag in online games
Why someone, who just wanted to look at some hitbox properties while warming up in practice, has to restart the game before hopping into ranked, without being identified as a cheater? Why is a person that doesn't have malicious intentions getting a ricochet? Actual people that are using frame data tools to gain an advantage vs people online, are going to move back to Tekken Bot Prime, so in the end everyone is a loser in this situation.
My suggestion is to either rework it, so the [overlay] shows only while actually using it in a real online match, or remove it completely so it won't bother anyone.

**Comment by thoraero** [comment]
Honestly I only use it in player match to learn the matchup. It's too tedious to keep guessing by getting hit over and over. Could you honorable developer sir show whatever needed only in ranked match? Let least give us lower ranks some room to grow quick?

**Comment by Snorgy** [comment]
Yeah it would be a lot better just having the overlay pop up on ranked, as I use player matches to learn matchups as well. Tekken is already a game with crazy amount of legacy skill granting advantages to players, so someone like me that has joined a few months ago would have years to memorize the hit and block data for thousands of strings and throw breaks across dozens of characters.

Instead I can accelerate my growth by popping into player matches and getting smacked around while being able to see that the move that keeps causing me to get counter hit is actually +3, and so I shouldn't press a button there. I can take that and then try and apply it later without the overlay in ranked.

If the point is to only use it in practice mode, well I can already see frame data there so the program becomes pointless for me. I tried just using it in player matches openly (a mode you gain/lose nothing) and people started to dodge and refuse to fight. After a few of those I just turned it off and see no reason to use it anymore.

I'm fine with keeping it out of ranked where things matter, but right now its counter productive even in player matches, a mode used for warming up/practice against other people and that gives no rewards other than a challenging fight.

**Comment by DennisStanistan** [comment]
> I am 100% behind the idea of informing people that you use overlay to your advantage against players online. But right now, this feature is harmful to: a) for people that want to take an advantage out of it (good)
> b) people that just want to use it for practice mode purposes
> c) for people that were using it to actually measure lag in online games
> Why someone, who just wanted to look at some hitbox properties while warming up in practice, has to restart the game before hopping into ranked, without being identified as a cheater? Why is a person that doesn't have malicious intentions getting a ricochet? Actual people that are using frame data tools to gain an advantage vs people online, are going to move back to Tekken Bot Prime, so in the end everyone is a loser in this situation.
> My suggestion is to either rework it, so the [overlay] shows only while actually using it in a real online match, or remove it completely so it won't bother anyone.

rework it? how about disabling the overlay completely during online ranked?

i'm shaking my head at you silly cheaters

**Comment by Snorgy** [comment]
It not working at all in ranked sounds great to me over this overlay thing.

**Comment by manishguptaji** [comment]
+1

**Comment by manishguptaji** [comment]
Most of us use this overlay to learn the matchup quickly, I don't want to lab every character.
And as far as online tournaments are concerned there are other frame data overlays as well. 
So adding [overlay] tag just force those people to look for other options than this overlay.

**Comment by ParkourGrip** [comment]
There is nothing wrong with learning the matchup quickly while playing. However, hiding the fact that you are trying to learn the matchup using a tool and pretending that the matches you are playing with the overlay can be used as a proof that you are better then someone else is malicious.

**Comment by thoraero** [comment]
Such a strong opinion stating as if it's a universal fact sir.

**Comment by Snorgy** [comment]
If the issue is knowledge over actual use, then the numbers can be delayed to make them impossible to be useful actively. Slap a 20-30 frame delay on the floating numbers and now they are useless as an active advantage in any match, but still allow you to learn after the fact. Its the equiv of having someone tell you "That is -13, you should be able to punish that." without giving you a clear indication to do so mid fight.

**Comment by solidfake** [comment]
To add upon the idea of Snorgy, just make it that only e.g. the last 5 frames show the numbers, with adjustable how long they stay after that. So e.g. if someone does a -17 OB move, it will show you the number only from frame 12 onward. Same for throws.

The other concern I've heard was that some moves that get different values depending on stance transitions can give you the unfair advantage. Disable it for those transitions explicitly, Done.

Regarding the tag: If it's possible to check which mode someone is playing, I'd agree with it being automatically disabled for ranked and tournament lobbies. But as someone else said, if you would completely disable it then it would be a useless tool as the whole point of it is seeing the data mid-match. What I'd personally would even like to see it being enable for ranked, but only up to a certain rank where it gets then disabled automatically.
What I'm much MORE concerned is that when you get labeled with the tag, it could give Murray the idea of banning players for it. I doubt they actually care and will do anything against all the hacks, but the guy is insane enough to might consider it. The fear is there, and as I can't stand playing Tekken without the overlay anymore because it saves so much time labbing, I will probably lay off the Tekken at all and focus on different games.

In general to all the unfair advantage concerns: Even if you remove all the issues that really might make it possible to abuse to react to it, players will still be either pro or contra to it, solely depending on how much time they've already spent labbing and memorizing. It is a learning tool, and therefore allows you to "skip" steps, and people will never like others doing it when they themselves didn't. It is just the same as with the netdecking phenomena of trading card games. So it's not really much a point arguing with such opinions, because it solely depends on which side of the fence you grew up.

**Comment by ParkourGrip** [comment]
> The other concern I've heard was that some moves that get different values depending on stance transitions can give you the unfair advantage. Disable it for those transitions explicitly, Done.

Easier said then done.

**Comment by HallwayRaptor** [comment]
I would love to see a separate too that shows ping, frame time, custom fps, etc. I don't want to be viewed as a cheater for wanting to see connection info.

**Comment by ParkourGrip** [comment]
> I would love to see a separate tool that shows ping, frame time, custom fps, etc. I don't want to be viewed as a cheater for wanting to see connection info.
That's reasonable. 
However... 
Some people still see custom FPS as cheating because it allows you to reduce your input lag by almost a full frame.
On the best connection possible or offline Tekken has 2 frames of input lag.
One of these frames is a game logic tick (locked on 60 updates/s) and one of these frames is a render frame (can be unlocked with the tool).
By setting your fps to 250 input lag of your game is reduced from 33.3 ms to 20.6 ms.
This effectively gives you 10ms faster reaction time. 
Connection info could give you information on whether to go for a high execution combo or a safe combo.
To me, little details like this only mater in serious competitions like online tournaments with prize money.

**Comment by solidfake** [comment]
If 10 ms less input lag is considered cheating, then so would be playing without vsync. Or playing with devices and drivers that themselves offer better tickrates.

There are tons of unfair advantages people can get, like low response monitors. Already playing on a better PC than someone else could be considered cheating then. If someone gets triggered by 10 ms, you better not listen to them in the first place. Especially considering offline tournaments are still played on playstation, making this a whole lot funnier.

**Comment by ParkourGrip** [comment]
According to [these](https://www.rtings.com/monitor/tests/inputs/input-lag) tests if you are running 250 fps and a average gaming monitor in order for your opponent to have the same input lag as you he would need to have a monitor with 0 ms input lag and that dose not exist.

**Comment by bluepill** [comment]
I'll soon be releasing an updated binary with this disabled.
ETA ~4-5 days since I'm currently travelling.

**Comment by WAZAAAAA0** [comment]
> I'll soon be releasing an updated binary with this disabled.
> ETA ~4-5 days since I'm currently travelling.

@bluepill I'm at least 5 parallel universes ahead of you my broski https://github.com/WAZAAAAA0/TekkenBot/issues/36 happy april fools' day TekkenOverlay colleagues :^)

**Comment by bluepill** [comment]
@WAZAAAAA0 
Awesome, thanks for your fast turnaround. I'm trapped with shitty airport WiFi and worse my remote vm won't load lol. Appreciate your help broski...

**Comment by DennisStanistan** [comment]
> If 10 ms less input lag is considered cheating, then so would be playing without vsync. Or playing with devices and drivers that themselves offer better tickrates.
>
> There are tons of unfair advantages people can get, like low response monitors. Already playing on a better PC than someone else could be considered cheating then. If someone gets triggered by 10 ms, you better not listen to them in the first place. Especially considering offline tournaments are still played on playstation, making this a whole lot funnier.

turning off vsync isn't considered cheating when it's an option given by the developers. faster reaction time is fine and well when it comes to games like csgo **where the developers didn't put a frame cap** and you can turn off literally everything and get a higher hertz monitor to get the best advantage possible. **tekken 7 has a 60 fps cap on purpose and unlocking it gives you an unfair advantage**. it's not a difficult concept to understand

**Comment by solidfake** [comment]
Yee, you are right, difference is who has access to the options.

I personally don't care if someone has 10 ms less input lag onto me, but when you really really want to ensure equal footing, for pros it might make a difference.

**Comment by ParkourGrip** [comment]
I wonder how long will it take me to update the overlay next time if you guys keep acting like this. 
I'm starting to think that this project is not worth maintaining. 
I'll keep this in mind next time a Tekken update brakes the overlay.
Also when it comes to new features like sidestep detection and string tree visualization I'm slowly loosing interest when it comes to implementing these.

You guys are acting like a bunch of children that can't live with compromises in life.
Both today and yesterday I played like 4 hours with the overlay name tag and every single player I encountered was nice and not a single guy plugged.
If you really believe that the advantage that the overlay gives you is too small to matter then you should not be ashamed of being open to your opponent about using it.

Yes there might be some features that may not require the name change like online lag and ping and there are probably ways to reset your name to normal before the overlay shuts down.
In the future the big advantage features like frame data, throw brakes, custom fps and exact health values will probably get disabled in ranked.
And there is always going to have to be the "[overlay]" tag in player matches because how else would you prevent users from using it in tournaments while still allowing users to have private matches with each other using the overlay. 
I'm not sure about quick matches but I'm fine with how things are now.

**Comment by solidfake** [comment]
> I wonder how long will it take me to update the overlay next time if you guys keep acting like this.
> I'm starting to think that this project is not worth maintaining.
> I'll keep this in mind next time a Tekken update brakes the overlay.
> Also when it comes to new features like sidestep detection and string tree visualization I'm slowly loosing interest when it comes to implementing these.
> 
> You guys are acting like a bunch of children that can't live with compromises in life.

I think it is more childish to "threaten" to no longer maintain it if ya'll can't behave. You guys did an amazing job and it is a great tool. You implemented a kinda controversial update to an already controversial mod, that is mandatory which also brought the mod again into the spotlight. This was to be expected. Shunning all discussion about that is not very open minded and it is a sensitive topic which you should as well treat that way. There'd valid discussion to be had about what is and isn't fair and how things could be better implemented. 

> If you really believe that the advantage that the overlay gives you is too small to matter then you should not be ashamed of being open to your opponent about using it.

I think no one thinks that. It is a clear advantage, both for learning the game and in general considering all features , that's why people use it. And that's why it's controversial and deserves discussion.

**Comment by ParkourGrip** [comment]
Ok from what I see here what needs to be done is following:

Separate advantageous features from the regular ones:
 - Adventageous: `frame data`, `throw tech`, `health values and distance`, `fps unlock`
 - Regular: everything else
 
Advantageous features are always disabled in ranked and in order to use them elsewhere a name tag needs to be applied to inform the opponent that they are being used.

In order to use the overlay in player matches the name tag needs to be applied no matter what to prevent any abuse in online tournaments.

**Comment by ParkourGrip** [comment]
Now give me 1 year to implement these.

**Comment by WAZAAAAA0** [comment]
my broski stop it you're trying too hard, you should be thinking about open sourcing the project rather than adding more convoluted layers of obfuscation lmao. Btw working hitboxes for projectiles when??

reminder that if the actual devs bothered to add proper QoL features to their game from the start (complete frame data/hit boxes/ping counters etc. and for free of course LMAO), there would've been no incentive to create TekkenBotPrime and TekkenOverlay in the first place. We wouldn't be here questioning the legality of these informational tools being used in different modes, because they would be TRAINING MODE exclusives. The game wouldn't be filled with auto-blockers/auto-throw-breakers that are taking advantage of the fact that we're constantly updating the memory addresses required for both the legit and non-legit tools to function lol

**Comment by ParkourGrip** [comment]
If I were to take a guess. 
Most of these script kids that make the auto-block and auto-brake scripts probably just download the source code of TBP and some custom python to it.
I don't think they even know how to use the memory addresses without the base code of TBP.
Open sourcing this project would just give them more tools to modify this overlay, make it a cheat and sell it for ezy $.

**Comment by DennisStanistan** [comment]
> If I were to take a guess.
> Most of these script kids that make the auto-block and auto-brake scripts probably just download the source code of TBP and some custom python to it.
> I don't think they even know how to use the memory addresses without the base code of TBP.
> Open sourcing this project would just give them more tools to modify this overlay, make it a cheat and sell it for ezy $.

use templates for everything and refactor the code to be the most confusing, messy, convoluted, non documented, optimized mess the world has ever seen. that'll probably stop 99% of the script kids

**Comment by ParkourGrip** [comment]
> use templates for everything and refactor the code to be the most confusing, messy, convoluted, non documented, optimized mess the world has ever seen. that'll probably stop 99% of the script kids

What you said makes absolutely 0 sense.
I'm not going to make my programming experience hell just to make a bunch of you that want the source code happy,

**Comment by wlsvyh** [comment]
It's a pity that it seems to be turning into an emotional discussion.
Tekken 7 is an e-sports event in which professional athletes sponsored by sponsors participate in prize money competitions. As the developers say, even subtle differences can lead to unfair results. We live in an era where all competitions are held online, and we agree that factors that can affect win or lose should be excluded. I support the developers.

If users can use it without revealing it in Quick Match, where users can enjoy the game without burden, except for ranked matches and player matches for online tournaments, it seems to reduce their regrets somewhat. If the overlay can differentiate between player matches and quick matches.

**Comment by olokos** [comment]
I'm definitely also against removing the [overlay] tag for people using it.

From what I know the main goal of this project is to actually learn the game better.
To be honest if the FPS Unlocked feature would be separate, that would be the only thing I would be using.

Ya know, it doesn't feel right to play 60FPS game which can dip below 60FPS on 144Hz G-Sync monitor, where G-Sync working range is between 60-144Hz. Any dips below 60FPS is making the game more stuttery and it's very obvious to notice.

I think that the [overlay] tag should be visible in all of the online games.

The only instance where it would be invisible would be if somebody would go online, but with all features giving an advantage against the enemy disabled.

kinda like

if(advantageOverTheEnemyFeatureisON){
   display [overlay];
}
else{
   don't display [overlay];
}

From my perspective FPS unlocker doesn't give any advantage over the enemies, only provides smoother and more pleasant gameplay, but I might be wrong about this one and I'd fully understand if this feature enabled would still display overlay clantag.

**Comment by olokos** [comment]
I've even wrote this problem to Harada on twitter
https://twitter.com/olokos1/status/1375056742057443332
But it seems it was completely disregarded, so I guess I'll keep using FPS Unlocker using the overlay, even though I'd rather not use anything to be able to play the game above 60FPS...

**Comment by DennisStanistan** [comment]
> > use templates for everything and refactor the code to be the most confusing, messy, convoluted, non documented, optimized mess the world has ever seen. that'll probably stop 99% of the script kids
> 
> What you said makes absolutely 0 sense.
> I'm not going to make my programming experience hell just to make a bunch of you that want the source code happy,

ye you're right it makes 0 sense. it's either that or people will just reverse engineer your shit and nop the function that sets the overlay tag anyway

here are two solutions that will make sense in the long run, preventing the overlay from functioning entirely in ranked and whoever manages to get a dll file without it/reverse-engineer it and disable it then let them cheat in peace like the dwelling sweaty losers they are OR just abandon the project entirely

**Comment by ParkourGrip** [comment]
Well at-least they will not turn it into a proper cheat like auto low block and auto throw brake.

**Comment by justatempnamefornow** [comment]
> I wonder how long will it take me to update the overlay next time if you guys keep acting like this.
> I'm starting to think that this project is not worth maintaining.
> I'll keep this in mind next time a Tekken update brakes the overlay.
> Also when it comes to new features like sidestep detection and string tree visualization I'm slowly loosing interest when it comes to implementing these.
> 
> You guys are acting like a bunch of children that can't live with compromises in life.
> Both today and yesterday I played like 4 hours with the overlay name tag and every single player I encountered was nice and not a single guy plugged.
> If you really believe that the advantage that the overlay gives you is too small to matter then you should not be ashamed of being open to your opponent about using it.
> 
> Yes there might be some features that may not require the name change like online lag and ping and there are probably ways to reset your name to normal before the overlay shuts down.
> In the future the big advantage features like frame data, throw brakes, custom fps and exact health values will probably get disabled in ranked.
> And there is always going to have to be the "[overlay]" tag in player matches because how else would you prevent users from using it in tournaments while still allowing users to have private matches with each other using the overlay.
> I'm not sure about quick matches but I'm fine with how things are now.

sorry but this blows my mind. People try and have a true discussion about something, unhappy or not. And you threaten people by saying your just not gonna update it next time. What is this. Of course there was gonna be some backlash to this. But the childish thing is you reacting the way you did instead of just brushing it aside. At the end of the day, its yall's code. Do what you want. No need to try and threaten people into behaving the way you want, thats NEVER gonna work

**Comment by ParkourGrip** [comment]
Ok, next time it needs a update I'm gonna waste 1 month implementing anti reverse engineering techniques so that the name change gets cracked 1 day later then normally. :)

**Comment by vissegard** [comment]
Or just abandon the idea, and let everyone be happy. It's not like people that are talking about cheating problem in Tekken are having main issues with people that "suspiciously" seem to know the matchup. Most people have trouble against macro users, autolowblockers and auto throwbreakers, and Tekken Overlay isn't even close to them. Tekken Overlay doesn't provide automatic punish to every thing that your opponent throws in your face being -, it provides you by information
And yeah, the idea completely backfired, people either gonna reverse engineer it, migrate to TGP (no, it's really not a huge deal to just go back to TGP from TO)

**Comment by justatempnamefornow** [comment]
> Ok, next time it needs a update I'm gonna waste 1 month implementing anti reverse engineering techniques so that the name change gets cracked 1 day later then normally. :)

Lmao, you do you my guy. If that's what you wanna do with it. Then go for it. Like I said after all its YOUR stuff. And if you wanna even stop doing it, thats OKAY. Your not the only overlay out there after all  👍 Thank you for your time makin this

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
I proudly wear my [overlay] tag as a badge of honor which proves i'm willing to learn the game

**Comment by justatempnamefornow** [comment]
> I proudly wear my [overlay] tag as a badge of honor which proves i'm willing to learn the game

Thats not my issue now. My issue is how the creator of this can't get over himself and seems to think if anyone disagrees there idiots

**Comment by justatempnamefornow** [comment]
I don't think it has anything at this point to show if your "willing to learn the game or not" Its Parkour bein childish af and acting like no one can disagree with him or what he does. And if we do hes gonna "punish us by not updating" I havent seen a SINGLE overlay tag. Prob cuz most people stopped using it or did what I did and switched to tekkenbotprime

**Comment by thoraero** [comment]
> I don't think it has anything at this point to show if your "willing to learn the game or not" Its Parkour bein childish af and acting like no one can disagree with him or what he does. And if we do hes gonna "punish us by not updating" I havent seen a SINGLE overlay tag. Prob cuz most people stopped using it or did what I did and switched to tekkenbotprime

This is all about the developer's "ideology" how the program should be used. Who are we to argue with him?
I just hope that this ideology was not "encouraged" somehow by Bandai Namco. 
P.s. Part of the reasons that you have not seen any overlay tag could be that some ppl have ways to work around that. Me included.

**Comment by justatempnamefornow** [comment]
> > I don't think it has anything at this point to show if your "willing to learn the game or not" Its Parkour bein childish af and acting like no one can disagree with him or what he does. And if we do hes gonna "punish us by not updating" I havent seen a SINGLE overlay tag. Prob cuz most people stopped using it or did what I did and switched to tekkenbotprime
> 
> This is all about the developer's "ideology" how the program should be used. Who are we to argue with him?
> I just hope that this ideology was not "encouraged" somehow by Bandai Namco.
> P.s. Part of the reasons that you have not seen any overlay tag could be that some ppl have ways to work around that. Me included.

that could be very true. Tbh id even appreciate you tellin me how <3 If not is all okay too. I always got botprime even if its not as good lmao.

**Comment by Xalraroz** [comment]
i would only use it for like the healthbar

**Comment by justatempnamefornow** [comment]
I mean, the only reason i give a fuck is i think the creator was rude af responding to people's criticism, was really childish. Not everyone is gonna agree with what he thinks and he obv couldn't handle it

**Comment by maciejkpl** [comment]
> I mean, the only reason i give a fuck is i think the creator was rude af responding to people's criticism, was really childish. Not everyone is gonna agree with what he thinks and he obv couldn't handle it

This is a great free tool. Im happy it exists. I personally think the [overlay] tag should be also implemented in TBP.  
@justatempnamefornow If somebody is childish here - its you.

**Comment by RogerDodger** [comment]
I know it sucks to have a bunch of entitled kids making demands of a free project so I thought I should comment that TekkenOverlay is invaluable to me for filling in the wiki. I'd be gutted if the project got abandoned just cause some whiners are upset they can't use it discreetly online. People who are happy with it as is aren't likely to stumble over here, which leads to some over-represented negativity.

**Comment by JackMcCallum** [comment]
@RogerDodger Theres a wiki with hitbox/frame info?

**Comment by RogerDodger** [comment]
@JackMcCallum Yeah, <https://wavu.wiki/>. It started back in December 2020 when the TZ wiki shutdown. I use TekkenOverlay frequently for frame history, recovery values, and debug variables when writing pages. The equivalent data from TBP are not as reliable.

**Comment by justatempnamefornow** [comment]
> I know it sucks to have a bunch of entitled kids making demands of a free project so I thought I should comment that TekkenOverlay is invaluable to me for filling in the wiki. I'd be gutted if the project got abandoned just cause some whiners are upset they can't use it discreetly online. People who are happy with it as is aren't likely to stumble over here, which leads to some over-represented negativity.

Again, I NEVER said i thought it was a bad thing to add. I just simply think Parkour is a bitch for lashing out at even the people who support all his changes/decisions because the voice of the few got to him a lil too much. I called him out. That is all. I still stand by thinkin parkour needs to either STOP caring what people think of what he wants to do with something HE created. OR just stop workin on it all together. Both of those are GREAT options rather then "wah wah if you ever say you don't like somethin I do again imma make sure I take longer to update to make you even more mad *cry cry sob sob*" Neither have I EVER made a demand for the overlay. You pulled that outta your booty hole like crazy. I think the Tag was a GREAT edition to stop use in tourny play (Even if the work around to stop it from appearing is super easy to use/find out. Me along with EVERYONE ELSE who isn't an idiot still use the overlay the exact same way as before lmao)

**Comment by JackMcCallum** [comment]
The reason the [overlay] feature was implemented was due to the overwhelming cries from people complaining about it (mostly PMs being sent to me on twitter and videos being made about it) being used in a competetive setting. especially online tournaments. like it or not. we made the decision to implement it and thats that. The mod was never intended for cheating and people have labeled it as a cheat.

For those who dont like it, the feature is here to stay, sorry.

Yes, ParkourGrip could have handled it better, we get it, ya'll need to calm your tits.

**Comment by justatempnamefornow** [comment]
Again, I think the tag is a GOOD thing. Yea you right i reacted wrong to Parkour, just don't like that type of person and it rubs me the wrong way super bad and gets me more then a lil salty. I do apologize though. No matter what yall do tho, there is always gonna be a work around the tag. Hell I was usin one within the first week of the tag bein added. It's just pointless to truly have it IMO. Atleast for somethin like ranked. There has to be a way to make it viable for tourny tho. Even tho it truly won't sway the outcome of it by much if ANY. Maybe in the starting brackets when people are trash and just trynna enter for the hell of it. By the end of most tournys (atleast bigger ones) people are not stupid af and mash tf outta unsafe strings 24/7 and know how to deal with stuff bein sent there way. The overlay wouldn't cause the good players to lose much more often if any

**Comment by ParkourGrip** [comment]
You can stay assured that as the game updates the older versions of the overlay will be more and more incompatible with the game and the tag is going to be harder and harder to bypass.

**Comment by DennisStanistan** [comment]
@justatempnamefornow If someone's gonna play ranked and they're gonna see that their opponent has the overlay tag and they know what it means then they have plenty of options. ALT+F4, not rematch or ignore it and play

>  No matter what yall do tho, there is always gonna be a work around the tag. Hell I was usin one within the first week of the tag bein added. It's just pointless to truly have it IMO.

Then you all have to ask yourselves. Are you looking for frame tool that can help you when you're practicing, or a cheat to use online without anyone knowing? You have an unfair advantage over someone in a ranked play and most players won't want to deal with an opponent that has an unfair advantage in a ranked, tournament or even casual setting. How's that concept difficult to understand?

If someone's gonna bypass it or make a similar tool without the overlay tag then no one's going to stop them sure but I think that Jack and ParkourGrip realize the basic concept of fair online play even if it's just by putting a band aid on the problem and not completely disabling the overlay online

>  There has to be a way to make it viable for tourny tho. Even tho it truly won't sway the outcome of it by much if ANY. Maybe in the starting brackets when people are trash and just trynna enter for the hell of it. By the end of most tournys (atleast bigger ones) people are not stupid af and mash tf outta unsafe strings 24/7 and know how to deal with stuff bein sent there way.

You have a tool that works online which can be used in tournaments. Tournaments that often have a large prize pool and are hosted by official/big organizers.

If you're not concerned about a random player who's unlikely to win the tournament even with an overlay then I'm sorry to inform that it still compromises tournament integrity, there were legit players who lost against the player in the process. How is that fair to them, whether they are _"trash, stupid and mash tf outta unsafe strings 24/7"_ or not? What will you say once a well known pro player starts using the overlay? What will you say if he gets caught?

**Comment by DennisStanistan** [comment]
> I won't care

@justatempnamefornow Well that's your problem. Most people care about that and that's why the overlay tag was added. There are strong arguments that are in favor for the overlay tag/disabling the overlay online than ones that are against it. If you're looking for a cheat that works online and won't expose you for being a scrub then look elsewhere. Rambling on and on about the developer won't change ParkourGrip's mind

> Doubt, your ability isn't better then everyone big boy

@ParkourGrip I think the community wants a challenge and is ready for the overlay to be completely disabled online, how does that sound?

**Comment by ParkourGrip** [comment]
There are going to be some changes around this feature next update.
Some features will be accessible without the [overlay] tag from now on.
Of course this dose not include frame numbers and throw tech.
Told you guys to give me a year ;)

**Comment by ParkourGrip** [comment]
Resloved in: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/4.25.0

**Comment by justatempnamefornow** [comment]
> There are going to be some changes around this feature next update. Some features will be accessible without the [overlay] tag from now on. Of course this dose not include frame numbers and throw tech. Told you guys to give me a year :)

You actually are a child arent you lmfao? Guess what... I got ANOTHER work around for this one too! Your so full of yourself its insane

**Comment by DennisStanistan** [comment]
> You actually are a child arent you lmfao? Guess what... I got ANOTHER work around for this one too! Your so full of yourself its insane

funny how you went from "I think the tag is a GOOD thing. i reacted wrong to Parkour" to "haha i bypassed your tag you're so full of yourself"
