### ISSUE TITLE
Frequent complete crashes when alt-tabbing with overlay running

### ISSUE THREAD

**Issue by pakirambo** [TekkenOverlay/TekkenOverlay#48]
The crash is so bad that I can see nothing except the game screen. Can go to the ctrl alt del menu and open task manager but its no use since the game window is still covering the entire screen and there is no way to get to task manager to end process. Only option is restarting.

**Comment by ParkourGrip** [comment]
I can't replicate that since it dose not crash for me however I do know that the overlay crashes the game if you change the in-game resolution.
The way i close Tekken when it crashes without restarting the PC is I switch to another virtual desktop with "Ctrl+Win+left/right" and open the Task Manager there to kill it.
If you already opened Task Manager on the same virtual desktop as Tekken you need to open up "Task view" and drag task manager to a different virtual desktop.
One way to significantly increase the Alt+Tab speed from full screen games and therefore reduce the probability of Tekken crashing is to disable EVERYTHING in "Focus assist" settings menu in Windows 10.
That's the feature that automatically disables/enables windows notifications when you go in and out of games but makes Alt+Tab-ing significantly slower as a result.
