### ISSUE TITLE
Few hair accessories become absurdly (!) big when Overlay is on

### ISSUE THREAD

**Issue by guy-jin** [TekkenOverlay/TekkenOverlay#58]
I don't know how many there might be but the ones I noticed were "Daruma Game Hair Accessory" and "Electric Fan Hair Accessory". These 2 become so extremely huge on screen that you can barely see anything when playing, while others function normally.

![20211230182230_1](https://user-images.githubusercontent.com/96887157/147783505-b359710a-6303-4c84-8b85-bcf2b3d68bcc.jpg)
![20211230182621_1](https://user-images.githubusercontent.com/96887157/147783510-bcb80223-10b1-4eba-8d3b-6ca9578d29ab.jpg)
![20211230183159_1](https://user-images.githubusercontent.com/96887157/147783512-f151a701-9049-457f-b53f-c77c62d60a37.jpg)

**Comment by ParkourGrip** [comment]
Could it be that all these items are attacked to the spine or root bones?

**Comment by ParkourGrip** [comment]
Anyway we had to use some advanced math to fix some animation issues that Namco introduced by having errors in the 60 fps animations they provide that are visible only if you start interpolating in-between these 60fps frames. 
Did you ever notice the visual bugs that happen only when the game runs in slowmo: https://youtu.be/H44De71N5T8?t=119
The problem is that the bones in some tekken animations instead of being rotated 90° for example. 
They are rotated like 180° and to fix the error all the child bones of that incorrectly rotated bone is rotated a extra 270° making the model be 180° + 270° = 450° rotated witch looks the same as being 90° rotated (450° - 360° = 90°). 
This is why you never see problems without slowmo. 
However when game goes into slowmo and starts interpolating frames the character rotates a extra 360° to go from 90° to  450° and that is what you see in the video above.
Now if we were to leave the animations as they are you would see these glitches while playing with Tekken Overlay's animation interpolation for these bugged animations every time (for the same reason you see them when tekken goes slowmo).

**Comment by ParkourGrip** [comment]
Anyway we had to use some advanced math to fix some animation issues that Namco introduced by having errors in the 60 fps animations they provide that are visible only if you start interpolating in-between these 60fps frames.
Did you ever notice the visual bugs that happen only when the game runs in slowmo: https://youtu.be/H44De71N5T8?t=119
The problem is that the bones in some tekken animations instead of being rotated 90° for example.
They are rotated like 180° and to fix the error all the child bones of that incorrectly rotated bone is rotated a extra 270° making the model be 180° + 270° = 450° rotated witch looks the same as being 90° rotated (450° - 360° = 90°).
This is why you never see problems without slowmo.
However when game goes into slowmo and starts interpolating frames the character rotates a extra 360° to go from 90° to 450° and that is what you see in the video above.
Now if we were to leave the animations as they are you would see these glitches while playing with Tekken Overlay's animation interpolation for these bugged animations every time (for the same reason you see them when tekken goes slowmo).

**Comment by ParkourGrip** [comment]
Anyway we had to use some advanced math to fix some animation issues that Namco introduced by having errors in the 60 fps animations they provide that are visible only if you start interpolating in-between these 60fps frames.

Did you ever notice the visual bugs that happen only when the game runs in slowmo: https://youtu.be/H44De71N5T8?t=119

The problem is that the bones in some Tekken animations instead of being rotated 90° for example.
They are rotated like 180° and to fix the error all the child bones of that incorrectly rotated bone is rotated a extra 270° making the model be 180° + 270° = 450° rotated witch looks the same as being 90° rotated (450° - 360° = 90°).
This is why you never see problems without slowmo.
However when game goes into slowmo and starts interpolating frames the character rotates a extra 360° to go from 90° to 450° and that is what you see in the video above.
Now if we were to leave the animations as they are you would see these glitches while playing with Tekken Overlay's animation interpolation for these bugged animations every time (for the same reason you see them when tekken goes slowmo).

Correct way to rotate a character: 
https://user-images.githubusercontent.com/1338621/147792131-440a39ac-4231-4bb5-8feb-68b1f9bfc19f.mp4
Namco way to rotate a character:
https://user-images.githubusercontent.com/1338621/147792170-0444f6d9-0347-42c2-9e0b-4454fcbf1ae9.mp4
Another example of this glitching out: 
https://user-images.githubusercontent.com/1338621/147792179-c6ec2db8-df7e-4448-a658-bec62076ee40.mp4

Now it's totally possible that our algorithm that fixes this errors introduces this problem.
I could imagine items that are attached to some of the bones that are close to the root bone getting bugged because of that.

**Comment by Yudoken** [comment]
Is there a mod to disable those specific items? Not gonna lie but encountering someone who's using one of the problematic items causes the match to be unplayable.

**Comment by Waistless** [comment]
Its not just attached accessories this can occur with - very rarely with high fps + interpolation on you might see the shoulder buddies like mokujin or the ghost become super size. 

https://user-images.githubusercontent.com/43065289/154801866-701a7d99-d2c0-41f8-b109-cae8cba7e2f7.mp4

![20220219223620_1](https://user-images.githubusercontent.com/43065289/154801894-33b87967-6a8e-4295-b659-ea5bccfcbf0d.jpg)

Not much of an issue for me with how rare it is, still funny though.

**Comment by ParkourGrip** [comment]
This update probably fixed this issue: https://github.com/TekkenOverlay/TekkenOverlay/releases/tag/5.00.0
I'll reopen the issue if it appears again.
