### ISSUE TITLE
The "Round 1 Fight!" Phase is going on and off too quick.

### ISSUE THREAD

**Issue by TheRevivalOfWisdom** [TekkenOverlay/TekkenOverlay#62]
Hello i am using the latest 4.26.2 version of Tekken Overlay. I am experiencing an annoying bug. Even if i disable the custom frame option in the overlay, when i activate overlay while i am in the game, the overlay automatically make the "Round x Fight!" sections before the match starts faster and making me have to wait for a second/ a second and half. i can do anything but to stand still (my inputs are locked) by 1/1.5 seconds and it is so annoying. This part of the custom frame property is bugged in my opinion. The worse thing is even if i disable the custom frame property of Tekken Overlay, this issue is still active. Can you guys do something about it asap?

Thanks for your understanding in advance

Sincerely

Take care.

**Comment by ParkourGrip** [comment]
This bug is caused by Namco making the speed of UI animations dependent on the frame-rate. 
If your game was to run on 30 FPS you would get the opposite problem, your game would play the "Fight" UI animation in slow motion and the round would start before the "Fight" world gets displayed.
Because your frame-rate is unlocked and is above 60, the "Fight" UI animation is sped up and that's why its not in sync with round start.
I suggest you time the round start based on sound and not the visual indication.
If you still don't like it you can lock the frame-rate back to 60 and the problem will go away.

**Comment by aptmac** [comment]
First of all, massive kudos for everyone that works on this mod - I started using it just for 144fps today and it's so cool.

Just spitballing over here, but is there any way to detect when intros are running, or perhaps have a timer run the duration of time while the round announcement is going? It'd be neat to have a dynamic fps option so it runs 60fps during intros and then goes back to whatever the user set in the overlay settings.

**Comment by ParkourGrip** [comment]
Someone did this recently. Did not test how well it works: https://tekkenmods.com/mod/1727/game-message-fix-for-120fps-cap
